update version
input-output-hk/sbt-verify pull request #3
Opened 2018-03-28 11:13 UTC by KonradStaniec

2018-03-29 15:21 UTC, loverdos requested changes

2018-03-29 15:21 UTC, loverdos commented on build.sbt
> +version := "0.4.0"
There already is a `v0.4.0` tag for a previous commit, so I think we need to bump it here to `0.4.1` and re-tag it as `v0.4.1`  after the new version is comitted.

2018-03-30 09:20 UTC, loverdos approved these changes

2018-03-30 09:52 UTC, LukasGasior1 approved these changes

2018-03-30 09:53 UTC, merged